# Generated by Django 4.1.7 on 2023-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image_big',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
